### ISSUE TITLE
How to build this project as a shared library?

### ISSUE THREAD

**Issue by rani-sharim** [FreeRTOS/corePKCS11#188] opened 2024-01-17 12:21 UTC
Hi, I'm not sure where to ask questions, so I'm posting it here.

I'm trying to use this library as a test target in my project, but I'm not that familiar with c++ and I'm not sure how to build it as an `.so` file to use like `softHSM` and such.

Any help would be appriciated.

**Comment by chinglee-iot** [comment] 2024-01-22 03:31
@rani-sharim
Thank you for the question about corePKCS11.
We would like to suggest you to post this question in [FreeRTOS forum](https://forums.freertos.org/).
There will be more support from community and your question can also benefit the forum users.
We intend to use Github issue primarily for bug tracking in this repository.
I am going to close this as this is not a bug.
Looking forward to see your post in FreeRTOS Forum.

**Closed by chinglee-iot** 2024-01-22 03:31 UTC
